# Project information
site_name: COVID-19 API
site_url: https://nat236919.github.io/covid19-api/
site_author: Nuttaphat Arunoprayoch
site_description: >-
  Simply Fast API for covid-19 cases exploration

# Repository
repo_name: nat236919/covid19-api
repo_url: https://github.com/nat236919/covid19-api
edit_uri: 

# Copyright
copyright: Copyright &copy; 2020 Nuttaphat Arunoprayoch

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nat236919
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/nat236919/covid19-api
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nat236919
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arunoprayoch-nuttaphat/

# Page tree
docs_dir: 'app'
nav:
  - Home: index.md
  - API documentation:
    - API v1: routers/v1/README.md
    - API v2: routers/v2/README.md
