# Project information
site_name: covid-19 API
site_url: https://nat236919.github.io/covid19-api/
site_author: Nuttaphat Arunoprayoch
site_description: >-
  Simply Fast API for covid-19 cases exploration

# Repository
repo_name: nat236919/covid19-api
repo_url: https://github.com/nat236919/covid19-api
edit_uri: 

# Copyright
copyright: Copyright &copy; 2020 Nuttaphat Arunoprayoch

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nat236919
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/nat236919/covid19-api
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nat236919
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arunoprayoch-nuttaphat/

# Page tree
nav:
  - Home: index.md
  - API documentation:
    - API v1: api_v1.md
    - API v2: api_v2.md
